import { assertEquals } from "jsr:@std/assert";

import { part1 } from "./day-6.ts";

export const TEST_INPUT = `....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...`;

Deno.test("part1", () => {
  assertEquals(part1(TEST_INPUT), 41);
});
